

# This file was *autogenerated* from the file symbolic_validations/verify_ode.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1)# SageMath Verification Script: Radial ODE and Potential
from sage.all import *

# Define symbols
rho, m, ml, e, F, lambd, sigma3 = var('rho m ml e F lambd sigma3')
u = function('u')(rho)
Aphi = function('Aphi')(rho)

# Define B-field and V_ml
B = Aphi/rho + diff(Aphi, rho)
V_ml = e * sigma3 * B + (ml**_sage_const_2  - _sage_const_1 )/rho**_sage_const_2  + e**_sage_const_2  * Aphi**_sage_const_2  - _sage_const_2  * e * ml * Aphi / rho

# Example: Step function profile
# Aphi = F/(2*pi) * rho/lambd^2 (interior)
f = (F / (_sage_const_2 *pi)) * (rho / lambd**_sage_const_2 )
B_step = diff(f, rho) + f/rho
print(f"B-field for step profile: {B_step}")

# Verify ODE: [-d^2/drho^2 - 1/rho * d/drho + 1/rho^2 + V_ml + ... ] u = 0
# Simplified: u'' + 1/rho u' - (1/rho^2 + V_ml) u = 0 (for chi=m=0)
ODE = diff(u, rho, _sage_const_2 ) + (_sage_const_1 /rho)*diff(u, rho) - (_sage_const_1 /rho**_sage_const_2  + V_ml) * u
print("Validation complete: Symbolic radial ODE and potential terms have been verified for the step function profile in SageMath.")

