

# This file was *autogenerated* from the file symbolic_validations/verify_asymptotics.sage
from sage.all_cmdline import *   # import sage library

from sage.all import *

def verify_high_chi_asymptotics():
    print("--- Verifying High-Chi Asymptotics of Green's Function Sum ---")
    s, m, eB, chi = var('s m eB chi')
    
    # tr G_2D(s) = (1/2*pi) * [eB / (2*sinh(seB))]
    # G0_2D(s) = (1/2*pi) * [1 / (2*s)]
    
    # Delta tr G_2D(s) = (1/4*pi) * [eB/sinh(seB) - 1/s]
    # Small s expansion:
    # sinh(x) approx x + x^3/6
    # 1/sinh(x) approx 1/x * (1 - x^2/6) = 1/x - x/6
    # [eB/sinh(seB) - 1/s] approx [1/s - seB^2/6 - 1/s] = -s*eB^2/6
    
    # Delta tr G_2D(chi) = integral ds e^(-s(chi^2+m^2)) * Delta tr G_2D(s)
    # Approx integral ds e^(-s chi^2) * (1/4*pi) * (-s*eB^2/6)
    # = -(eB^2 / 24*pi) * integral ds s e^(-s chi^2)
    # = -(eB^2 / 24*pi) * (1 / chi^4)
    
    print("\nAsymptotic Delta tr G_2D (High Chi):")
    print("Delta tr G_2D approx -(eB^2 / 24*pi) * (1 / chi^4)")
    
    # Sum of radial Green's functions:
    # sum G_radial / rho = 2*pi * Delta tr G_2D
    # sum G_radial / rho approx 2*pi * [-(eB^2 / 24*pi) * (1/chi^4)]
    # = -(eB^2 / 12) * (1/chi^4)
    
    print("\nRadial Mode Sum Asymptotics (High Chi):")
    print("sum Delta G_radial / rho approx -(eB^2 / 12) * (1 / chi^4)")
    
    # UV Subtraction term check:
    # If we want the spectral integral to converge, we subtract the leading 1/chi^4 term.
    # UV_sub = -(eB^2 / 12) * (1 / chi^4)
    
    # Note: Scalar QED field strength renormalization term is 1/6 (eB)^2 T^2 in worldline.
    # Let's check how that relates.
    # I_scal(T) = (e^-m^2T / T^3) * [Delta W + 1/6 (eBT)^2]
    # Small T: Delta W approx -1/6 (eBT)^2 + ...
    # So Delta W + 1/6 (eBT)^2 approx 0 + O(T^4)
    # This makes the integral integral dT/T^3 * O(T^4) = integral dT/T converge.
    # Wait, 1/T^3 * T^4 = T. So integral converges at T=0.
    
    # In spectral form:
    # integral chi^3 dchi * [sum Delta G_radial / rho + (eB^2 / 12 chi^4)]
    # Small chi behavior: sum Delta G is regular.
    # High chi behavior: [ -1/12 chi^4 + 1/12 chi^4 ] = 0
    # So integral integral chi^3 dchi * O(1/chi^6) converges at infinity.
    
    print("\nConclusion:")
    print("UV Subtraction term for (sum Delta G_radial / rho) should be +(eB^2 / 12) * (1/chi^4)")
    print("Wait, my code used B^2/6.")

if __name__ == "__main__":
    verify_high_chi_asymptotics()

